### ISSUE TITLE
ContainerBuilder doesn't have a virtual destructor

### ISSUE THREAD

**Issue by mauriziomacrina** [ybainier/Hypodermic#52]
Hello,
In [this](https://github.com/ybainier/Hypodermic/wiki/Merging-containers#inheriting-from-containerbuilder) section of the beginner guide, it's suggesting to inherit from the `ContainerBuilder` class.

However we have noticed that `ContainerBuilder` class doesn't have a virtual destructor.
Is that a bug? Inheriting from that class may cause undefined behaviour 

@ybainier - can you please clarify that? Thanks.

**Comment by ybainier** [comment]
Hi, you found a mistake that I fixed here: 5b60e84571e767b4c8c43f7b833a2553681f441c. Never came accross an issue because of that since our custom container builders don't have a state for themselves except the one they inherit from `ContainerBuilder` which is always deleted in whichever scenario.

Thank you for your help.
